# Generated by Django 5.2.9 on 2025-12-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('metabolism', 'Метаболизм'), ('vitamins', 'Витамины'), ('sport', 'Спорт'), ('sleep', 'Сон'), ('nutrition', 'Питание')], max_length=32)),
                ('rs_id', models.CharField(blank=True, max_length=32)),
                ('effect_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('sport', 'Спорт'), ('vitamins', 'Витамины'), ('sleep', 'Сон'), ('nutrition', 'Питание'), ('general', 'Общее')], max_length=32)),
                ('severity_level', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('daily_norm_value', models.FloatField(blank=True, null=True)),
                ('upper_limit_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('category', models.CharField(blank=True, choices=[('fat-soluble', 'Жирорастворимый'), ('water-soluble', 'Водорастворимый')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('genetics', 'Генетика'), ('metabolism', 'Метаболизм'), ('sport', 'Спорт'), ('vitamins', 'Витамины'), ('sleep', 'Сон')], max_length=32)),
                ('source_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='genapp.gene')),
            ],
        ),
        migrations.CreateModel(
            name='GeneVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.CharField(max_length=8)),
                ('risk_type', models.CharField(blank=True, max_length=16)),
                ('variant_description', models.TextField(blank=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='genapp.gene')),
            ],
        ),
        migrations.CreateModel(
            name='GeneVariantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.genevariant')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='UserGenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.genevariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=16)),
                ('diet_preferences', models.TextField(blank=True)),
                ('goals_text', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('seen', 'Просмотрена'), ('applied', 'Применена'), ('dismissed', 'Отклонена')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('normal', 'Норма'), ('at_risk', 'Риск дефицита'), ('deficient', 'Дефицит')], default='normal', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.vitamin')),
            ],
        ),
        migrations.CreateModel(
            name='GeneVitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(blank=True, max_length=32)),
                ('effect_description', models.TextField(blank=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.gene')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.vitamin')),
            ],
        ),
        migrations.CreateModel(
            name='VitaminGenotypeEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_level', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=16)),
                ('effect_text', models.TextField(blank=True)),
                ('gene_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.genevariant')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.vitamin')),
            ],
        ),
    ]
