# Generated by Django 5.2.9 on 2025-12-12 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='gene',
            options={'verbose_name': 'Ген', 'verbose_name_plural': 'Гены'},
        ),
        migrations.AlterModelOptions(
            name='genevariant',
            options={'verbose_name': 'Вариант гена', 'verbose_name_plural': 'Варианты генов'},
        ),
        migrations.AlterModelOptions(
            name='genevariantrecommendation',
            options={'verbose_name': "Связь 'Вариант гена — Рекомендация'", 'verbose_name_plural': "Связи 'Вариант гена — Рекомендация'"},
        ),
        migrations.AlterModelOptions(
            name='genevitamin',
            options={'verbose_name': 'Связь ген-витамин', 'verbose_name_plural': 'Связи ген-витамин'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='usergenotype',
            options={'verbose_name': 'Генотип пользователя', 'verbose_name_plural': 'Генотипы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userrecommendation',
            options={'verbose_name': 'Пользовательская рекомендация', 'verbose_name_plural': 'Пользовательские рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='uservitamin',
            options={'verbose_name': 'Статус витамина пользователя', 'verbose_name_plural': 'Статусы витаминов пользователей'},
        ),
        migrations.AlterModelOptions(
            name='vitamin',
            options={'verbose_name': 'Витамин', 'verbose_name_plural': 'Витамины'},
        ),
        migrations.AlterModelOptions(
            name='vitamingenotypeeffect',
            options={'verbose_name': 'Влияние генотипа на витамин', 'verbose_name_plural': 'Влияния генотипов на витамины'},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='severity_level',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=128, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('metabolism', 'Метаболизм'), ('sport', 'Спорт'), ('vitamins', 'Витамины'), ('nutrition', 'Питание')], max_length=32, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='gene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='genapp.gene', verbose_name='Ген'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='category',
            field=models.CharField(blank=True, choices=[('metabolism', 'Метаболизм'), ('vitamins', 'Витамины'), ('sport', 'Спорт'), ('nutrition', 'Питание')], max_length=32, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='effect_description',
            field=models.TextField(blank=True, verbose_name='Эффект'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='rs_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='rsID'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='symbol',
            field=models.CharField(max_length=32, unique=True, verbose_name='Символ'),
        ),
        migrations.AlterField(
            model_name='genevariant',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='genapp.gene', verbose_name='Ген'),
        ),
        migrations.AlterField(
            model_name='genevariant',
            name='genotype',
            field=models.CharField(max_length=8, verbose_name='Генотип'),
        ),
        migrations.AlterField(
            model_name='genevariant',
            name='risk_type',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=16, verbose_name='Тип риска'),
        ),
        migrations.AlterField(
            model_name='genevariant',
            name='variant_description',
            field=models.TextField(blank=True, verbose_name='Описание варианта'),
        ),
        migrations.AlterField(
            model_name='genevariantrecommendation',
            name='gene_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.genevariant', verbose_name='Вариант гена'),
        ),
        migrations.AlterField(
            model_name='genevariantrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.recommendation', verbose_name='Рекомендация'),
        ),
        migrations.AlterField(
            model_name='genevitamin',
            name='effect_description',
            field=models.TextField(blank=True, verbose_name='Описание влияния'),
        ),
        migrations.AlterField(
            model_name='genevitamin',
            name='effect_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тип влияния'),
        ),
        migrations.AlterField(
            model_name='genevitamin',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.gene', verbose_name='Ген'),
        ),
        migrations.AlterField(
            model_name='genevitamin',
            name='vitamin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.vitamin', verbose_name='Витамин'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(blank=True, choices=[('sport', 'Спорт'), ('vitamins', 'Витамины'), ('sleep', 'Сон'), ('nutrition', 'Питание'), ('general', 'Общее')], max_length=32, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='usergenotype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='usergenotype',
            name='gene_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.genevariant', verbose_name='Вариант гена'),
        ),
        migrations.AlterField(
            model_name='usergenotype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='usergenotype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=16, verbose_name='Уровень активности'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diet_preferences',
            field=models.TextField(blank=True, verbose_name='Пищевые предпочтения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=16, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goals_text',
            field=models.TextField(blank=True, verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.recommendation', verbose_name='Рекомендация'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('seen', 'Просмотрена'), ('applied', 'Применена'), ('dismissed', 'Отклонена')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='uservitamin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='uservitamin',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='uservitamin',
            name='status',
            field=models.CharField(choices=[('normal', 'Норма'), ('at_risk', 'Риск дефицита'), ('deficient', 'Дефицит')], default='normal', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='uservitamin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='uservitamin',
            name='vitamin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.vitamin', verbose_name='Витамин'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='category',
            field=models.CharField(blank=True, choices=[('fat-soluble', 'Жирорастворимый'), ('water-soluble', 'Водорастворимый')], max_length=32, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='daily_norm_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Дневная норма'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='unit',
            field=models.CharField(blank=True, max_length=16, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='upper_limit_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Верхний предел'),
        ),
        migrations.AlterField(
            model_name='vitamingenotypeeffect',
            name='effect_text',
            field=models.TextField(blank=True, verbose_name='Эффект'),
        ),
        migrations.AlterField(
            model_name='vitamingenotypeeffect',
            name='gene_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.genevariant', verbose_name='Вариант гена'),
        ),
        migrations.AlterField(
            model_name='vitamingenotypeeffect',
            name='impact_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=16, verbose_name='Уровень влияния'),
        ),
        migrations.AlterField(
            model_name='vitamingenotypeeffect',
            name='vitamin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.vitamin', verbose_name='Витамин'),
        ),
    ]
