# Generated by Django 5.2.9 on 2025-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0002_alter_article_options_alter_gene_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(blank=True, choices=[('sport', 'Спорт'), ('vitamins', 'Витамины'), ('nutrition', 'Питание'), ('general', 'Общее')], max_length=32, verbose_name='Категория'),
        ),
    ]
