# Generated by Django 5.2.9 on 2025-12-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0003_alter_recommendation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genevitamin',
            name='effect_type',
        ),
    ]
