# Generated by Django 5.2.9 on 2025-12-14 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0004_remove_genevitamin_effect_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamin',
            name='ref_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальное реф. значение'),
        ),
        migrations.AddField(
            model_name='vitamin',
            name='ref_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальное реф. значение'),
        ),
        migrations.CreateModel(
            name='BloodTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_value', models.FloatField(verbose_name='Результат анализа')),
                ('test_date', models.DateField(verbose_name='Дата сдачи анализа')),
                ('ref_min', models.FloatField(blank=True, null=True, verbose_name='Реф. минимум')),
                ('ref_max', models.FloatField(blank=True, null=True, verbose_name='Реф. максимум')),
                ('lab_name', models.CharField(blank=True, max_length=255, verbose_name='Название лаборатории')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оценки'), ('normal', 'В норме'), ('low', 'Дефицит'), ('high', 'Избыток')], default='pending', max_length=20, verbose_name='Статус')),
                ('deviation_percent', models.FloatField(blank=True, null=True, verbose_name='Отклонение от нормы, %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.vitamin', verbose_name='Витамин')),
            ],
            options={
                'verbose_name': 'Результат анализа крови',
                'verbose_name_plural': 'Результаты анализов крови',
                'ordering': ['-test_date'],
            },
        ),
    ]
