# Generated by Django 5.2.9 on 2025-12-14 19:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0005_vitamin_ref_max_vitamin_ref_min_bloodtestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservitamin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservitamin',
            name='vitamin',
        ),
        migrations.CreateModel(
            name='VitaminTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_value', models.FloatField(verbose_name='Результат анализа')),
                ('unit', models.CharField(max_length=16, verbose_name='Единицы измерения')),
                ('test_date', models.DateField(default=datetime.date.today, verbose_name='Дата анализа')),
                ('laboratory', models.CharField(blank=True, max_length=128, verbose_name='Лаборатория')),
                ('reference_min', models.FloatField(blank=True, null=True, verbose_name='Реф. минимум (лаб)')),
                ('reference_max', models.FloatField(blank=True, null=True, verbose_name='Реф. максимум (лаб)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('status', models.CharField(blank=True, choices=[('deficiency', 'Дефицит'), ('low', 'Понижен'), ('normal', 'Норма'), ('high', 'Повышен'), ('excess', 'Избыток')], max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitamin_tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genapp.vitamin', verbose_name='Витамин')),
            ],
            options={
                'verbose_name': 'Результат анализа на витамин',
                'verbose_name_plural': 'Результаты анализов на витамины',
                'ordering': ['-test_date'],
            },
        ),
        migrations.DeleteModel(
            name='BloodTestResult',
        ),
        migrations.DeleteModel(
            name='UserVitamin',
        ),
    ]
