# Generated by Django 5.2.9 on 2025-12-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0006_remove_uservitamin_user_remove_uservitamin_vitamin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitamintestresult',
            options={'ordering': ['-test_date', '-created_at'], 'verbose_name': 'Результат анализа на витамин', 'verbose_name_plural': 'Результаты анализов на витамины'},
        ),
        migrations.RemoveField(
            model_name='vitamintestresult',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='vitamintestresult',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vitamintestresult',
            name='reference_max',
        ),
        migrations.RemoveField(
            model_name='vitamintestresult',
            name='reference_min',
        ),
        migrations.AddField(
            model_name='vitamin',
            name='unit_test',
            field=models.CharField(blank=True, max_length=16, verbose_name='Ед. измерения в анализе'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='unit',
            field=models.CharField(blank=True, max_length=16, verbose_name='Ед. измерения прием внутрь'),
        ),
        migrations.AlterField(
            model_name='vitamintestresult',
            name='status',
            field=models.CharField(blank=True, choices=[('deficiency', 'Дефицит'), ('low', 'Ниже нормы'), ('normal', 'В норме'), ('high', 'Выше нормы'), ('excess', 'Избыток')], max_length=20, verbose_name='Статус'),
        ),
    ]
