# Generated by Django 5.2.9 on 2025-12-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0007_alter_vitamintestresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitamintestresult',
            options={'ordering': ['-test_date'], 'verbose_name': 'Результат анализа на витамин', 'verbose_name_plural': 'Результаты анализов на витамины'},
        ),
        migrations.RemoveField(
            model_name='vitamintestresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vitamintestresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vitamintestresult',
            name='unit',
        ),
    ]
