# Generated by Django 5.2.9 on 2026-04-02 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0008_alter_vitamintestresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('deleted', 'Удален')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_comments', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('genotype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_comments', to='genapp.usergenotype', verbose_name='К генотипу')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
                ('vitamin_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_comments', to='genapp.vitamintestresult', verbose_name='К анализу витамина')),
            ],
            options={
                'verbose_name': 'Комментарий врача',
                'verbose_name_plural': 'Комментарии врача',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorCommentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_text', models.TextField(verbose_name='Предыдущее содержание')),
                ('previous_status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('deleted', 'Удален')], max_length=16, verbose_name='Предыдущий статус')),
                ('previous_genotype_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Предыдущий генотип (id)')),
                ('previous_vitamin_test_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Предыдущий анализ витамина (id)')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='genapp.doctorcomment', verbose_name='Комментарий')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_comment_edits', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
            ],
            options={
                'verbose_name': 'История комментария врача',
                'verbose_name_plural': 'Истории комментариев врача',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patients', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_doctors', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Связь врач-пациент',
                'verbose_name_plural': 'Связи врач-пациент',
                'constraints': [models.UniqueConstraint(fields=('doctor', 'patient'), name='unique_doctor_patient')],
            },
        ),
    ]
