# Generated by Django 5.2.9 on 2026-04-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0012_inpersonappointment_patientnotification_appointment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inpersonappointment',
            new_name='genapp_inpe_patient_f013e7_idx',
            old_name='genapp_inpe_patient_2b5_idx',
        ),
        migrations.RenameIndex(
            model_name='inpersonappointment',
            new_name='genapp_inpe_doctor__48e409_idx',
            old_name='genapp_inpe_doctor_8a1_idx',
        ),
    ]
