# Generated by Django 5.2.9 on 2026-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0014_myth_truth_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='category',
            field=models.CharField(blank=True, choices=[('metabolism', 'Метаболизм'), ('vitamins', 'Витамины'), ('sport', 'Спорт'), ('nutrition', 'Питание'), ('skincare', 'Кожа и старение'), ('hair', 'Волосы'), ('longevity', 'Долголетие'), ('detox', 'Детоксикация'), ('hormones', 'Гормоны'), ('immunity', 'Иммунитет'), ('bones', 'Кости и суставы'), ('circadian', 'Циркадные ритмы')], max_length=32, verbose_name='Категория'),
        ),
    ]
