# Generated by Django 5.2.9 on 2026-04-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0015_alter_gene_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(blank=True, choices=[('sport', 'Спорт'), ('vitamins', 'Витамины'), ('nutrition', 'Питание'), ('general', 'Общее'), ('skincare', 'Кожа'), ('hair', 'Волосы'), ('longevity', 'Долголетие'), ('circadian', 'Режим / сон'), ('hormones', 'Гормоны'), ('detox', 'Детокс / антиоксиданты'), ('bones', 'Кости / кальций'), ('metabolism', 'Метаболизм')], max_length=32, verbose_name='Категория'),
        ),
    ]
