# Generated by Django 5.2.9 on 2026-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0016_recommendation_expand_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_personal_data_at',
            field=models.DateTimeField(blank=True, help_text='Момент выражения согласия на обработку персональных и медицинских данных в сервисе.', null=True, verbose_name='Согласие на обработку ПДн (дата/время)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_text_version',
            field=models.CharField(blank=True, default='1', max_length=32, verbose_name='Версия текста согласия'),
        ),
    ]
