# Generated by Django 5.2.9 on 2026-04-27 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genapp', '0019_symptomtestitem_cms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSymbolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32, verbose_name='Символ (нормализованный)')),
                ('raw_input', models.CharField(blank=True, default='', max_length=64, verbose_name='Как ввели')),
                ('proposed_genotype', models.CharField(blank=True, default='', max_length=32, verbose_name='Предполагаемый генотип')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий пациента')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('added', 'Добавлено в справочник'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='Примечание администратора')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_gene_symbol_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_symbol_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Заявка на добавление гена',
                'verbose_name_plural': 'Заявки на добавление генов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='genapp_gene_user_id_50cba1_idx')],
            },
        ),
    ]
